name: Check URLs

on: [push, pull_request]

jobs:
  urls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install awesome_bot
        run: gem install awesome_bot

      - name: Check URLs
        run: awesome_bot README.md --allow-redirect --request-delay 0.2 -w iec.ch,gost.ru,tcvn.gov.vn,tisi.go.th
